---
title: "Tompkins Cost Burd Map"
author: "dani smith"
date: "2023-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidycensus)
library(dplyr)
library(readr)
library(tmap)

#importing acs data with geometry points

tompkins_block_groups <- get_acs(
  geography = "block group",
  state = "NY",
  county = "Tompkins",
  year = 2021,
  variables = c(
    cost_burden = "B08134_073"
  ),
  geometry = TRUE
)|>
  select(GEOID,geometry,NAME, variable)

#importing online acs data (housing burden var was only available online)

tompk_rent_cost_burd <- read.csv("C:/Users/iamda/Downloads/ACS2021_Renter_Cost_Burden.csv")


tompkins_block_groups <- tompkins_block_groups |> 
    mutate(GEOID = as.numeric(GEOID))

#merging geometry map data and the imported acs cost burden data, removing one NA

rent_cost_burd_and_map <- tompkins_block_groups|>
  full_join(tompk_rent_cost_burd,join_by(GEOID))|>
  na.omit()

#mapping the data onto a choropleth with histogram legend

tm_shape(rent_cost_burd_and_map) + 
  tm_polygons(col = "prcb_acs",
              style = "quantile",
              n = 5,
              palette = "Purples",
              title = "2017-2021 ACS",
              legend.hist = TRUE)+
  tm_layout(title = "Percent of Renters\nCost Burdened\nby Block Group",
            frame = FALSE,
            legend.outside = TRUE,
            bg.color = "grey80",
            legend.hist.width = 5,
            fontfamily = "Verdana")

```