version: '3.8'

services:
  webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    restart: on-failure
    env_file:
      - .env  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${DATABASE_URL}
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    ports:
      - "8080:8080"
    entrypoint: >
      /bin/bash -c "
      apt-get update && apt-get install -y libpq-dev && 
      pip install --upgrade psycopg2-binary &&

      if [ ! -f /airflow_initialized ]; then
          echo 'Initializing Airflow DB...';
          airflow db init && airflow db upgrade;
          touch /airflow_initialized;
      else
          echo 'Airflow DB already initialized. Skipping db init.';
      fi;

      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com;

      airflow scheduler & exec airflow webserver"
