version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  webserver:
    image: apache/airflow:2.5.1
    container_name: airflow-webserver
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env  
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${DATABASE_URL}
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    ports:
      - "8080:8080"
    entrypoint: /bin/bash -c "if [ ! -f /airflow_initialized ]; then airflow db init && airflow db upgrade && touch /airflow_initialized; fi && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow scheduler & airflow webserver"
