name: Run Airflow DAG

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  run-dag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install apache-airflow pandas numpy psycopg2 requests overpy
      
      - name: Run Airflow DAG
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python backend/airflow/dags/housing_data_training.py
