name: Trigger Airflow DAG

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  trigger-airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        working-directory: backend/airflow
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      - name: Start Airflow with Docker
        working-directory: backend/airflow 
        run: |
          docker-compose -f docker-compose.yml up -d
          echo "Waiting for services to initialize..."
          sleep 30  # Ensure services get time to boot up

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to start..."
          until docker exec airflow_postgres pg_isready -h localhost -p 5432 -U postgres; do
            sleep 2
          done
          echo "Postgres is ready!"

      - name: Wait for Airflow Webserver to be ready
        run: |
          echo "Waiting for Airflow webserver..."
          until docker logs airflow-webserver 2>&1 | grep -q "Running the Gunicorn Server"; do
            sleep 2
          done
          echo "Airflow webserver is ready!"

      - name: Initialize and Upgrade Airflow DB
        run: |
          docker exec airflow-webserver airflow db init
          docker exec airflow-webserver airflow db upgrade

      - name: Trigger Airflow DAG
        run: |
          docker exec airflow-webserver airflow dags trigger retrain_rental_model

      - name: Show Airflow Logs (If DAG Fails)
        if: failure()
        run: |
          echo "Fetching logs for debugging..."
          docker logs airflow-webserver || echo "No logs found"
          docker logs airflow_postgres || echo "No logs found"

      - name: Clean up
        run: |
          docker-compose -f docker-compose.yml down
