name: Run Airflow DAG

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  run-dag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r backend/airflow/requirements.txt
          pip install apache-airflow-providers-postgres 

      - name: Initialize Airflow
        run: |
          export AIRFLOW_HOME=$GITHUB_WORKSPACE/backend/airflow  
          mkdir -p $AIRFLOW_HOME/logs/scheduler 
          airflow db init 
          airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email asmaitra2006@gmail.com
          
      - name: Test Database Connection
        run: |
          python -c "import psycopg2; conn = psycopg2.connect('${{ secrets.DATABASE_URL }}'); print('✅ DB Connection Successful!')"

      - name: Run Airflow DAG Manually
        run: |
          export AIRFLOW_HOME="$GITHUB_WORKSPACE/backend/airflow"  
          mkdir -p $AIRFLOW_HOME/logs/scheduler  
          airflow dags test retrain_rental_model $(date +"%Y-%m-%d")
