name: Trigger Airflow DAG

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  trigger-airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        working-directory: backend/airflow
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      - name: Start Airflow with Docker
        working-directory: backend/airflow 
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 60 

      - name: Trigger Airflow DAG
        run: |
          docker exec airflow-webserver airflow dags trigger retrain_rental_model

      - name: Clean up
        run: |
          docker-compose -f docker-compose.yml down
